# Generated by Django 5.1.4 on 2025-01-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productcategory_order_feedback_complaint_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
