# Generated by Django 5.2 on 2025-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_productcategory_description_delete_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('meter', 'meter'), ('Pack of 10 pcs', 'Pack of 10 pcs')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('fabric', 'fabric'), ('embllishments', 'embllishments')], max_length=40, null=True),
        ),
    ]
